<?php
declare(strict_types=1);

function master_services(): array
{
    return [
        [
            'id' => 'dashboard-radar',
            'name' => 'Radar Xavier',
            'category' => 'Marches',
            'href' => '/dashboard',
            'launchLabel' => 'Ouvrir le radar',
            'statusCheck' => ['type' => 'port', 'host' => '127.0.0.1', 'port' => 3000],
            'summary' => 'Le poste de pilotage marche: brief, TOP 3 radar, opportunites, news, macro et agents Xavier.',
            'result' => 'Une shortlist claire avec contexte, zones, invalidation, objectifs et score de revue avant de preparer la seance.',
            'tutorial' => [
                'Connecte-toi avec xav.',
                'Lance le brief de seance puis le scan news si le contexte est vieux.',
                'Lis le TOP 3 par marche, ouvre TradingView si besoin, puis valide seulement les setups propres.',
            ],
        ],
        [
            'id' => 'clips',
            'name' => 'Clips Morning Mood',
            'category' => 'Contenu',
            'href' => '/clips/',
            'launchLabel' => 'Ouvrir les clips',
            'statusCheck' => ['type' => 'port', 'host' => '127.0.0.1', 'port' => 8094],
            'summary' => 'Studio de clips et worker de traitement pour transformer les contenus Morning Mood en formats courts.',
            'result' => 'Des extraits prets a verifier, monter, sous-titrer et publier sans repartir du podcast complet.',
            'tutorial' => [
                'Depose ou selectionne le contenu source.',
                'Laisse le traitement extraire les passages forts et les transcripts.',
                'Recupere les clips proposes, verifie le texte, puis exporte les meilleurs formats.',
            ],
        ],
        [
            'id' => 'ivt-radar',
            'name' => 'IVT Radar',
            'category' => 'Marches',
            'href' => 'https://radar.ftfenaux.com/',
            'launchLabel' => 'Ouvrir IVT Radar',
            'statusCheck' => ['type' => 'port', 'host' => '127.0.0.1', 'port' => 8787],
            'summary' => 'Veille IVT autonome avec service quotidien programme a 07:15 heure de Paris.',
            'result' => 'Un radar de veille exploitable le matin pour reperer les sujets et signaux IVT a suivre.',
            'tutorial' => [
                'Ouvre le radar avec le compte xav.',
                'Controle la veille du matin et les signaux remontes.',
                'Garde uniquement ce qui merite une action ou une mention dans les contenus.',
            ],
        ],
        [
            'id' => 'ivt-newsletter',
            'name' => 'Newsletter IVT',
            'category' => 'Contenu',
            'href' => 'https://radar.ftfenaux.com/newsletter/',
            'launchLabel' => 'Ouvrir newsletter',
            'statusCheck' => ['type' => 'port', 'host' => '127.0.0.1', 'port' => 8790],
            'summary' => 'Dashboard newsletter connecte au radar IVT, avec brouillon quotidien programme a 07:30.',
            'result' => 'Un brouillon de newsletter alimente par la veille, pret a relire et ajuster.',
            'tutorial' => [
                'Ouvre la newsletter apres la generation du matin.',
                'Relis les blocs proposes et retire les signaux faibles.',
                'Finalise le ton, les titres et les liens avant envoi.',
            ],
        ],
        [
            'id' => 'strategy-x',
            'name' => 'Strategie X',
            'category' => 'Editorial',
            'href' => '/master/strategy.php',
            'launchLabel' => 'Ouvrir la strategie',
            'statusCheck' => ['type' => 'file', 'path' => __DIR__ . '/../dashboard/strategy/strategie_x_xfenaux_v7_source.html'],
            'summary' => 'Plan de publication X et base editoriale Xavier, accessible ici sous le login master.',
            'result' => 'Une strategie claire pour choisir les angles, posts et priorites de publication.',
            'tutorial' => [
                'Ouvre la strategie depuis le master.',
                'Choisis le pilier editorial du moment.',
                'Transforme les idees retenues en posts ou scripts courts.',
            ],
        ],
        [
            'id' => 'live',
            'name' => 'Deck Live',
            'category' => 'Presentation',
            'href' => '/live/',
            'launchLabel' => 'Ouvrir le deck',
            'statusCheck' => ['type' => 'file', 'path' => __DIR__ . '/../live/index.html'],
            'summary' => 'Support live Xavier/IVT pour derouler une presentation propre en plein ecran.',
            'result' => 'Un deck pret pour animer une sequence live avec navigation simple.',
            'tutorial' => [
                'Ouvre le deck avant le live.',
                'Passe en plein ecran.',
                'Utilise les fleches ou le clic pour avancer slide par slide.',
            ],
        ],
        [
            'id' => 'tournage-ivt',
            'name' => 'Tournage IVT',
            'category' => 'Production',
            'href' => 'https://ftfenaux.com/tournageivt/',
            'launchLabel' => 'Ouvrir tournage',
            'statusCheck' => ['type' => 'http', 'url' => 'https://ftfenaux.com/tournageivt/'],
            'summary' => 'Interface de tournage IVT en ligne, servie par le service PM2 tournageivt.',
            'result' => 'Un espace pret pour cadrer et piloter les contenus de tournage IVT.',
            'tutorial' => [
                'Ouvre l interface de tournage.',
                'Prepare la sequence avant enregistrement.',
                'Utilise le retour visuel pour garder le deroule propre.',
            ],
        ],
        [
            'id' => 'ivtday',
            'name' => 'IVT Day',
            'category' => 'Evenement',
            'href' => '/ivtday/',
            'launchLabel' => 'Ouvrir IVT Day',
            'statusCheck' => ['type' => 'file', 'path' => __DIR__ . '/../ivtday/index.html'],
            'summary' => 'Experience evenementielle IVT Day avec telecommande websocket quand le serveur remote est actif.',
            'result' => 'Une presentation evenementielle controlee a distance si le module IVT Remote est operationnel.',
            'tutorial' => [
                'Ouvre la page IVT Day sur l ecran principal.',
                'Ouvre la telecommande sur /ivtday/remote.html si disponible.',
                'Controle les slides et videos depuis la telecommande pendant l evenement.',
            ],
        ],
        [
            'id' => 'actualites',
            'name' => 'Archives IVT',
            'category' => 'Editorial',
            'href' => '/actualit%C3%A9s/',
            'launchLabel' => 'Ouvrir archives',
            'statusCheck' => ['type' => 'file', 'path' => __DIR__ . '/../actualités/index.php'],
            'summary' => 'Archive publique des journees et contenus IVT deja publies sur le site Xavier.',
            'result' => 'Un historique consultable pour reutiliser un sujet, une preuve ou une sequence.',
            'tutorial' => [
                'Ouvre les archives.',
                'Selectionne la date IVT pertinente.',
                'Recupere les angles et references reutilisables.',
            ],
        ],
        [
            'id' => 'site-xavier',
            'name' => 'Site Xavier',
            'category' => 'Public',
            'href' => '/',
            'launchLabel' => 'Voir le site',
            'statusCheck' => ['type' => 'file', 'path' => __DIR__ . '/../index.html'],
            'summary' => 'Site public de Xavier Fenaux, avec page vitrine et prise de contact Morning Mood.',
            'result' => 'Une presence publique propre qui oriente les visiteurs vers les demandes et contenus Xavier.',
            'tutorial' => [
                'Controle la premiere impression du site.',
                'Verifie les liens et la photo principale apres chaque modification.',
                'Teste la demande de rendez-vous si une campagne renvoie vers le site.',
            ],
        ],
        [
            'id' => 'analytics',
            'name' => 'Analytics',
            'category' => 'Pilotage',
            'href' => 'https://analytics.ftfenaux.com/',
            'launchLabel' => 'Ouvrir analytics',
            'statusCheck' => ['type' => 'http', 'url' => 'https://analytics.ftfenaux.com/'],
            'summary' => 'Suivi d audience Umami pour verifier les visites et l impact des pages.',
            'result' => 'Une lecture rapide des pages vues, sources et tendances apres publication.',
            'tutorial' => [
                'Ouvre Analytics.',
                'Filtre sur le domaine Xavier si necessaire.',
                'Compare les pages actives et les sources apres les publications.',
            ],
        ],
    ];
}

