<?php
declare(strict_types=1);

function master_services(): array
{
    return [
        [
            'id' => 'brief-mood',
            'name' => 'Brief Mood',
            'category' => 'Contenu',
            'href' => '/brief-mood/',
            'launchLabel' => 'Ouvrir le brief',
            'statusCheck' => ['type' => 'http', 'url' => 'https://xavierfenaux.com/brief-mood/'],
            'summary' => 'Le brief du matin : actualités vérifiées, version podcast et sources séparées.',
            'result' => 'Un brief prêt à relire, compléter avec tes polarités et copier. Envoi quotidien à 04:00, heure de Paris.',
            'tutorial' => [
                'Ouvre l’édition du jour et vérifie les actualités retenues.',
                'Ajoute tes polarités ; si nécessaire, ajuste la sélection et relance la rédaction.',
                'Copie le brief ou la version podcast. Les preuves restent dans Actualités & sources.',
            ],
        ],
        [
            'id' => 'clips',
            'name' => 'Clips Morning Mood',
            'category' => 'Contenu',
            'href' => '/clips/',
            'launchLabel' => 'Ouvrir les clips',
            'statusCheck' => ['type' => 'http', 'url' => 'https://xavierfenaux.com/clips/'],
            'summary' => 'Studio de clips et worker de traitement pour transformer les contenus Morning Mood en formats courts.',
            'result' => 'Des extraits prets a verifier, monter, sous-titrer et publier sans repartir du podcast complet.',
            'tutorial' => [
                'Depose ou selectionne le contenu source.',
                'Laisse le traitement extraire les passages forts et les transcripts.',
                'Recupere les clips proposes, verifie le texte, puis exporte les meilleurs formats.',
            ],
        ],
        [
            'id' => 'ivt-radar',
            'name' => 'IVT Radar',
            'category' => 'Marches',
            'href' => 'https://radar.ftfenaux.com/',
            'launchLabel' => 'Ouvrir IVT Radar',
            'statusCheck' => ['type' => 'http', 'url' => 'https://radar.ftfenaux.com/'],
            'summary' => 'Veille IVT autonome avec service quotidien programme a 07:15 heure de Paris.',
            'result' => 'Un radar de veille exploitable le matin pour reperer les sujets et signaux IVT a suivre.',
            'tutorial' => [
                'Ouvre le radar : ton accès est transmis automatiquement depuis le cockpit.',
                'Controle la veille du matin et les signaux remontes.',
                'Garde uniquement ce qui merite une action ou une mention dans les contenus.',
            ],
        ],
        [
            'id' => 'site-xavier',
            'name' => 'Site Xavier',
            'category' => 'Public',
            'href' => '/',
            'launchLabel' => 'Voir le site',
            'statusCheck' => ['type' => 'file', 'path' => __DIR__ . '/../index.html'],
            'summary' => 'Site public de Xavier Fenaux, avec page vitrine et prise de contact Morning Mood.',
            'result' => 'Une presence publique propre qui oriente les visiteurs vers les demandes et contenus Xavier.',
            'tutorial' => [
                'Controle la premiere impression du site.',
                'Verifie les liens et la photo principale apres chaque modification.',
                'Teste la demande de rendez-vous si une campagne renvoie vers le site.',
            ],
        ],
        [
            'id' => 'analytics',
            'name' => 'Analytics',
            'category' => 'Pilotage',
            'href' => '#analytics',
            'launchLabel' => 'Voir les statistiques',
            'statusCheck' => ['type' => 'file', 'path' => '/var/lib/xavier-master/analytics.json'],
            'summary' => 'Suivi d audience Umami pour verifier les visites et l impact des pages.',
            'result' => 'Une lecture rapide des pages vues, sources et tendances apres publication.',
            'tutorial' => [
                'Ouvre Analytics.',
                'Les statistiques sont déjà filtrées sur le site de Xavier.',
                'Compare les pages actives et les sources apres les publications.',
            ],
        ],
        [
            'id' => 'social-x',
            'name' => 'X',
            'category' => 'Reseaux',
            'href' => 'https://x.com/XFenaux',
            'launchLabel' => 'Ouvrir X',
            'statusCheck' => ['type' => 'http', 'url' => 'https://x.com/XFenaux'],
            'stats' => [
                ['label' => 'Compte', 'value' => '@XFenaux'],
                ['label' => 'Stats auto', 'value' => 'API X requise'],
                ['label' => 'A suivre', 'value' => 'posts, reponses, impressions'],
            ],
            'summary' => 'Canal court pour les prises de position, reactions marche et posts issus de la strategie editoriale.',
            'result' => 'Une lecture rapide de ce qui prend: sujets, accroches, reponses et angles a recycler.',
            'tutorial' => [
                'Ouvre X depuis le master.',
                'Regarde les posts recents, les reponses et les sujets qui creent le plus d echanges.',
                'Note les accroches qui peuvent devenir un clip, un Morning Mood ou un post plus long.',
            ],
        ],
        [
            'id' => 'social-instagram',
            'name' => 'Instagram',
            'category' => 'Reseaux',
            'href' => 'https://www.instagram.com/xfenaux/',
            'launchLabel' => 'Ouvrir Instagram',
            'statusCheck' => ['type' => 'http', 'url' => 'https://www.instagram.com/xfenaux/'],
            'stats' => [
                ['label' => 'Compte', 'value' => '@xfenaux'],
                ['label' => 'Abonnes publics', 'value' => '2 317'],
                ['label' => 'Publication', 'value' => 'Reels et posts'],
            ],
            'summary' => 'Canal visuel pour reels, extraits, coulisses et signaux de presence personnelle Xavier.',
            'result' => 'Une vue simple des formats qui meritent d etre pousses ou adaptes en clips.',
            'tutorial' => [
                'Ouvre Instagram.',
                'Controle les derniers reels et posts.',
                'Reprends les formats qui gardent le mieux l attention ou declenchent des messages.',
            ],
        ],
        [
            'id' => 'social-tiktok',
            'name' => 'TikTok',
            'category' => 'Reseaux',
            'href' => 'https://www.tiktok.com/@interactivtrading',
            'launchLabel' => 'Ouvrir TikTok',
            'statusCheck' => ['type' => 'http', 'url' => 'https://www.tiktok.com/@interactivtrading'],
            'stats' => [
                ['label' => 'Compte', 'value' => '@interactivtrading'],
                ['label' => 'Stats auto', 'value' => 'Connexion dans Mes comptes'],
                ['label' => 'A suivre', 'value' => 'vues, retention, partages'],
            ],
            'summary' => 'Profil TikTok officiel InteractivTrading.',
            'result' => 'Les videos publiees sur @interactivtrading. La synchronisation se configure dans Mes comptes.',
            'tutorial' => [
                'Ouvre le profil @interactivtrading.',
                'Retrouve les videos publiees sur le compte.',
                'Dans Mes comptes, autorise TikTok pour synchroniser les statistiques disponibles.',
            ],
        ],
    ];
}
